export default {
  'sex': 'Пол',
  'alive': 'Жив(а)',
  'dead': 'Мертв(а)',
  'born': 'Рождение',
  'surnameAtBirth': 'Фамилия при рождении',
  'placeOfBorn': 'Место рождения',
  'addKinship': 'Добавить родство',
  'father': 'Отец',
  'mother': 'Мать',
  'daughter': 'Дочь',
  'son': 'Сын',
  'editRelation': 'Редактировать связи',
  'makeMain': 'Сделать главной персоной',
  'newRelation': 'Новая связь',
  'deletePerson': 'Удалить персону',
  'deleteRelation': 'Удалить связь',
  'invite': 'Пригласить',
  'listAndCreate': 'Список деревьев и создание нового',
  'searchPersons': 'Поиск персон в дереве',
}